@startuml image
title over Internet-MQTTでの実装イメージ
cloud AWS{
    card S3{
        component WebPage
    }
    card IoTCore{
        component MQTTMessageBroker
    }
}
node 屋外{
    actor 俺
    card Mobile{
        card WebBrowser{
            component JsPaho
        }
    }
}
node 家{
    card miniCar{
        card RaspberryPi{
            component PythonPaho
            card GPIO
        }
        card DCMotor 
        card ServoMotor
        GPIO-->DCMotor
        GPIO-->ServoMotor
    }
}
WebPage-down->WebBrowser:download
JsPaho-down->MQTTMessageBroker:MQTT publish
PythonPaho<-up-MQTTMessageBroker:MQTT subscribe
@enduml
